# Generated by Django 3.1.5 on 2021-01-18 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20210117_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='expenses.budget'),
        ),
    ]
