# Generated by Django 3.1.5 on 2021-01-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20210122_1703'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['slug'], name='slug_index'),
        ),
    ]
